//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgCooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communaute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Communaute()
        {
            this.Comment = new HashSet<Comment>();
            this.Recettes = new HashSet<Recettes>();
        }
    
        public string firstname { get; set; }
        public string surname { get; set; }
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> level { get; set; }
        public string picture { get; set; }
        public string city { get; set; }
        public string birth { get; set; }
        public string bio { get; set; }
        public string UsersId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recettes> Recettes { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
